{% extends bento_base_template %}
{% block SETUP_BENTO_COMPONENTS %}
{{ super() }}
{% block SETUP_BENTO_BASE_IMAGE %}
FROM public.ecr.aws/lambda/python:3.8


RUN mkdir /app
WORKDIR /app

COPY inference_svc.py .

{{ super() }}
{% endblock %}
{% block SETUP_BENTO_COMPONENTS %}
{{ super() }}

{% endblock %}